version: "3.3"


services:
  db:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  tg_bot:
    container_name: tg_bot
    restart: always
    build: .
    depends_on:
      - db
